/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.statemachine.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.statemachine.ui.internal.StatemachineActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class StatemachineExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(StatemachineActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		StatemachineActivator activator = StatemachineActivator.getInstance();
		return activator != null ? activator.getInjector(StatemachineActivator.ORG_XTEXT_EXAMPLE_STATEMACHINE_STATEMACHINE) : null;
	}

}
