/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.statemachine.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class StatemachineUiModule extends AbstractStatemachineUiModule {

	public StatemachineUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
