/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.statemachine.statemachine.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.statemachine.statemachine.InitialState;
import org.xtext.example.statemachine.statemachine.StatemachinePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Initial State</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class InitialStateImpl extends AbstractStateImpl implements InitialState
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InitialStateImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return StatemachinePackage.Literals.INITIAL_STATE;
  }

} //InitialStateImpl
