/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.statemachine.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractStatemachineScopeProvider extends DelegatingScopeProvider {
}
