/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.statemachine.ide;


/**
 * Use this class to register ide components.
 */
public class StatemachineIdeModule extends AbstractStatemachineIdeModule {
}
