/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.statemachine;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class StatemachineStandaloneSetup extends StatemachineStandaloneSetupGenerated {

	public static void doSetup() {
		new StatemachineStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
