/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.statemachine.statemachine;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Final State</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.statemachine.statemachine.StatemachinePackage#getFinalState()
 * @model
 * @generated
 */
public interface FinalState extends AbstractState
{
} // FinalState
