/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.statemachine.statemachine;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>State</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.statemachine.statemachine.State#getActivities <em>Activities</em>}</li>
 *   <li>{@link org.xtext.example.statemachine.statemachine.State#getStates <em>States</em>}</li>
 *   <li>{@link org.xtext.example.statemachine.statemachine.State#getTransitions <em>Transitions</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.statemachine.statemachine.StatemachinePackage#getState()
 * @model
 * @generated
 */
public interface State extends AbstractState
{
  /**
   * Returns the value of the '<em><b>Activities</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.statemachine.statemachine.Activity}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Activities</em>' containment reference list.
   * @see org.xtext.example.statemachine.statemachine.StatemachinePackage#getState_Activities()
   * @model containment="true"
   * @generated
   */
  EList<Activity> getActivities();

  /**
   * Returns the value of the '<em><b>States</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.statemachine.statemachine.AbstractState}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>States</em>' containment reference list.
   * @see org.xtext.example.statemachine.statemachine.StatemachinePackage#getState_States()
   * @model containment="true"
   * @generated
   */
  EList<AbstractState> getStates();

  /**
   * Returns the value of the '<em><b>Transitions</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.statemachine.statemachine.Transition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transitions</em>' containment reference list.
   * @see org.xtext.example.statemachine.statemachine.StatemachinePackage#getState_Transitions()
   * @model containment="true"
   * @generated
   */
  EList<Transition> getTransitions();

} // State
