/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.statemachine.statemachine;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Transition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.statemachine.statemachine.Transition#getStart <em>Start</em>}</li>
 *   <li>{@link org.xtext.example.statemachine.statemachine.Transition#getEnd <em>End</em>}</li>
 *   <li>{@link org.xtext.example.statemachine.statemachine.Transition#getActivity <em>Activity</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.statemachine.statemachine.StatemachinePackage#getTransition()
 * @model
 * @generated
 */
public interface Transition extends EObject
{
  /**
   * Returns the value of the '<em><b>Start</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start</em>' reference.
   * @see #setStart(AbstractState)
   * @see org.xtext.example.statemachine.statemachine.StatemachinePackage#getTransition_Start()
   * @model
   * @generated
   */
  AbstractState getStart();

  /**
   * Sets the value of the '{@link org.xtext.example.statemachine.statemachine.Transition#getStart <em>Start</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start</em>' reference.
   * @see #getStart()
   * @generated
   */
  void setStart(AbstractState value);

  /**
   * Returns the value of the '<em><b>End</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>End</em>' reference.
   * @see #setEnd(AbstractState)
   * @see org.xtext.example.statemachine.statemachine.StatemachinePackage#getTransition_End()
   * @model
   * @generated
   */
  AbstractState getEnd();

  /**
   * Sets the value of the '{@link org.xtext.example.statemachine.statemachine.Transition#getEnd <em>End</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>End</em>' reference.
   * @see #getEnd()
   * @generated
   */
  void setEnd(AbstractState value);

  /**
   * Returns the value of the '<em><b>Activity</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Activity</em>' containment reference.
   * @see #setActivity(Activity)
   * @see org.xtext.example.statemachine.statemachine.StatemachinePackage#getTransition_Activity()
   * @model containment="true"
   * @generated
   */
  Activity getActivity();

  /**
   * Sets the value of the '{@link org.xtext.example.statemachine.statemachine.Transition#getActivity <em>Activity</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Activity</em>' containment reference.
   * @see #getActivity()
   * @generated
   */
  void setActivity(Activity value);

} // Transition
