/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.statemachine.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.statemachine.ui.internal.StatemachineActivator;

public class StatemachineUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return StatemachineActivator.getInstance().getInjector("org.xtext.example.statemachine.Statemachine");
	}

}
